### PR TITLE
seperate guesser role

### PR DESCRIPTION
**Pull request by SonOfMars90**
Seperated the "Guesser" Role into two unique roles: "Evil Guesser" and "Nice Guesser".

Each can be configured in the menu.

- chance of being spawed
- number of shoots

There is no more option/chance that allows the guesser to be evil **or** nice.

### CODE REVIEW

**Comment by Peybro** [comment]
Evil and Nice Guessers are actually already in the game..?! 🤔

**Comment by SonOfMars90** [comment]
At the moment, the Guesser ist a unique role wich can apply as an Evil Guesser or Nice Guesser, but not at the same time.

This change gives us a unique Evil Guesser and a unique Nice Guesser, both can apply at the same time.

**Comment by Eisbison** [comment]
Does it make sense to have both an Evil and a Good Guesser at the same time? :D To me that feels a little much :)

**Comment by Eisbison** [comment]
Also please set up the PR properly, otherwise there's no way that someone can look at it  (there shouldn't be 5k line changes ;) )

**Comment by SonOfMars90** [comment]
For my lobby  and me it does make sense, everyone is happy about that and we have some funny and nice Evil Guesser vs. Nice Guesser shoot outs. But I can see your point. Maybe there is a solution, that makes it possible to have both variants in the game and each lobby can play like they want.

Ok, i will look what went wrong, the Chamaleon Role has the same problem.

**Pull request closed without merging**
