### PR TITLE
Fix all bugs

### PR DESCRIPTION
**Pull request by EoF-1141**
Can't have bugs, if there is no code

### CODE REVIEW

**Comment by Eisbison** [comment]
Lol, that's like 42... the perfect answer

**Comment by amsyarasyiq** [comment]
lmao

**Comment by nokoji** [comment]
PR approved, please merge.

**Comment by divinity76** [comment]
If we do this, then mark my words, features ***will*** break!

**Comment by Niknovk** [comment]
It’s good

**Pull request closed without merging**
