### PR TITLE
Add color to the winners' names in the End Game Screen (according to their team)

### PR DESCRIPTION
**Pull request by gendelo3**
This simple PR will add colors to the winning players in the end game screen.

- The losers' names will stay white
- If the winner is in a special team (i.e. not crew or impostor), the winning names will have that team's color
- Otherwise, the winners' color will be red in losing clients, and "victory-blue" in winning clients.

This is really just a small addition in order to be able to see who is winning and losing at one glance.

Discord feature request:
https://discord.com/channels/818086884089659412/825225643285282838/910884166525132821

### CODE REVIEW

**Comment by dwd0tcom** [comment]
But don't we have already a big screen which shows the winner?

**Comment by gendelo3** [comment]
Yes, and in that screen the names are shown in white, and the winning players' characters are shown. But you can't see the losers at one glance, you have to conclude them from their roles.

It's really only a small detail, and I think the details are part of what makes this mod superior compared to others.

**Comment by Eisbison** [comment]
As we now display the name + role in every case there for the winners, I think we can close this PR right? :) Anyways thank you for the contribution.

**Comment by gendelo3** [comment]
Most surely, yours looks better too!

**Pull request closed without merging**
