### PR TITLE
Guesser info chat message for ghosts

### PR DESCRIPTION
**Pull request by gendelo3**
With this feature, the player that died due to a guess will automatically post a chat message in the ghost chat containing the player and the role that was guessed by a guesser and whether it was correct or not.

This message can be turned off in the game options by the lobby host.

### CODE REVIEW

**Comment by gendelo3** [comment]
Feature suggestion here: 
https://discord.com/channels/818086884089659412/825225643285282838/876047769494757416

**Comment by Eisbison** [comment]
I actually like this little feature a lot, I'll see if we can add this with the next update :) Thank you for your contribution and for keeping it updated :)

**Comment by gendelo3** [comment]
You're very welcome, thanks for this amazing mod!

**Comment by gendelo3** [comment]
Closing, as this is now in the mod (and even in a way so that the guesser doesn't get banned anymore).

**Pull request closed without merging**
